{"uuid": "fa5769a3-a485-46b0-aed9-d0202342aa56", "children": ["c55d3ca2-fbb6-4244-8b40-c44855c0365b"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\Web_Testing\\Tests\\signup_tests.py\", line 29, in setup\n    self.driver.get(self.link)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1585792370564, "stop": 1585792370564}], "start": 1585792370564, "stop": 1585792370614}