{"uuid": "61f77b5c-99d5-4df9-b06f-9e3eb5ff873f", "children": ["6fbbd22a-9bf0-47f3-bde6-dff98ae699e4"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\Web_Testing\\Tests\\signup_tests.py\", line 29, in setup\n    self.driver.get(self.link)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1585792370294, "stop": 1585792370294}], "start": 1585792370294, "stop": 1585792370344}