{"uuid": "451b3ac6-d592-4b65-b01a-cf85d89685af", "children": ["3d9f555e-e5cd-4d7a-b6da-ec99414f76e3"], "befores": [{"name": "setup", "status": "passed", "start": 1586743624686, "stop": 1586743705030}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/KIMO/Desktop/Testing/Web_Testing/Tests/test_premium.py\", line 60, in setup\n    self.driver.delete_all_cookies()\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 878, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586743705646, "stop": 1586743707273}], "start": 1586743624686, "stop": 1586743707273}