{"name": "Check right information", "status": "broken", "statusDetails": {"message": "SystemExit: Testing failed in account overview with credentials : test3@test.com & test345", "trace": "self = <Web_Testing.Pages.AccountOverviewPage.AccountOverviewPage object at 0x04F05820>, email = 'test3@test.com', password = 'test345'\ndob = <Web_Testing.helperClasses.DOB object at 0x04F05940>, username = 'Testing TeamX'\n\n    def account_overview_check(self, email, password, dob, username):\n        try:\n            # if not check_account_overview_page():\n            # self.helper.click_button_safe(self.account_overview_btn)\n    \n            if self.initialize_account_overview():\n>               if self.is_correct_email(email) and self.is_correct_dob(dob) and self.is_correct_username(username):\n\nWeb_Testing\\Pages\\AccountOverviewPage.py:135: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Web_Testing.Pages.AccountOverviewPage.AccountOverviewPage object at 0x04F05820>, email = 'test3@test.com'\n\n    def is_correct_email(self, email):\n>       if self.get_account_overview_email() == email:\n\nWeb_Testing\\Pages\\AccountOverviewPage.py:112: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Web_Testing.Pages.AccountOverviewPage.AccountOverviewPage object at 0x04F05820>\n\n    def get_account_overview_email(self):\n>       account_overview_email = self.account_overview_elements[1].text\nE       IndexError: list index out of range\n\nWeb_Testing\\Pages\\AccountOverviewPage.py:98: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Web_Testing.Tests.test_accountoverview.TestAccountOverview object at 0x04EED6B8>, setup_check_information = None\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.story(\"Account Overview Tests\")\n    @allure.sub_suite(\"Check right information\")\n    @allure.title(\"Check right information\")\n    @allure.description(\"Check user information and signing in with the following credentials email : \"\n                        \"test_projectX@hotmail.com & password: \")\n    @pytest.mark.Do\n    @pytest.mark.AccountOverview\n    def test_case_1(self, setup_check_information):\n        account_overview_page = AccountOverviewPage(self.driver)\n        account_overview_page.click_account()\n        time.sleep(3)\n>       if account_overview_page.account_overview_check(\"test3@test.com\",\n                                                        ConstantsClass().get_pass(\"test3@test.com\"),\n                                                        ConstantsClass().get_dob(\"test3@test.com\"),\n                                                        ConstantsClass().get_name(\"test3@test.com\")):\n\nWeb_Testing\\Tests\\test_accountoverview.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nWeb_Testing\\Pages\\AccountOverviewPage.py:149: in account_overview_check\n    exit('Testing failed in account overview with credentials : ' + email + \" & \" + password)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Use exit() or Ctrl-Z plus Return to exit, code = 'Testing failed in account overview with credentials : test3@test.com & test345'\n\n    def __call__(self, code=None):\n        # Shells like IDLE catch the SystemExit, but listen when their\n        # stdin wrapper is closed.\n        try:\n            sys.stdin.close()\n        except:\n            pass\n>       raise SystemExit(code)\nE       SystemExit: Testing failed in account overview with credentials : test3@test.com & test345\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\_sitebuiltins.py:26: SystemExit"}, "description": "Check user information and signing in with the following credentials email : test_projectX@hotmail.com & password: ", "start": 1586057730560, "stop": 1586057733626, "uuid": "fb6af762-ef42-47d8-8d2d-01526ff7c15e", "historyId": "c38811e362e09239520d458ec3ff2c89", "testCaseId": "f8495a297c2ea54805288fbb7cefa284", "fullName": "Web_Testing.Tests.test_accountoverview.TestAccountOverview#test_case_1", "labels": [{"name": "parentSuite", "value": "End to End testing"}, {"name": "suite", "value": "Account Overview Tests"}, {"name": "story", "value": "Account Overview Tests"}, {"name": "subSuite", "value": "Check right information"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Account Overview Tests"}, {"name": "tag", "value": "AccountOverview"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "Eman"}, {"name": "thread", "value": "34868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Web_Testing.Tests.test_accountoverview"}]}