{"name": "Login with wrong email", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "SUCCESS: Login failed with incorrect credentials", "source": "cdf55d83-f64a-42b2-8580-5e1fb903a5dd-attachment.png", "type": "image/png"}], "start": 1584857417995, "stop": 1584857427714, "uuid": "82dbde1b-9519-4517-a96f-ac2b47b00aa7", "historyId": "9aa68b1871d3b3962c9a317f03448176", "testCaseId": "edd1d0640244c5b16184751388881064", "fullName": "Web_Testing.Tests.test_signin.TestLogin#test_case_3", "labels": [{"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "story", "value": "Failing login"}, {"name": "suite", "value": "Login Tests"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "7784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Web_Testing.Tests.test_signin"}]}