{"name": "Login with wrong email", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "SUCCESS: Login failed with incorrect credentials", "source": "ae43c7c8-9b50-46e3-a1f0-d37c09c59435-attachment.png", "type": "image/png"}], "start": 1584338027799, "stop": 1584338037472, "uuid": "ce525932-3cb3-416d-a34d-23f7ad4aaa45", "historyId": "b9ca19a10222315a5ea05b954dc66a1d", "testCaseId": "ea1582cff99b4a6d96e3e94b3ca92adf", "fullName": "Tests.test_signin.TestLogin#test_case_3", "labels": [{"name": "story", "value": "Failing login"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "4440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_signin"}]}