{"name": "Login with empty password", "status": "broken", "statusDetails": {"message": "SystemExit: Testing failed in login with credentials : mohdos_1999@hotmail.com &", "trace": "self = <Web_Testing.Pages.login.LoginPage object at 0x000002914FCD1D48>, email = 'mohdos_1999@hotmail.com', password = ''\n\n    def login_to_spotify(self, email, password):\n        # timeout for login\n        timeout = 5\n        try:\n>           self.clear_credentials() # clear email and password fields\n\nPages\\login.py:93: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Web_Testing.Pages.login.LoginPage object at 0x000002914FCD1D48>\n\n    def clear_credentials(self):\n>       self.email_txt.clear()\nE       AttributeError: 'NoneType' object has no attribute 'clear'\n\nPages\\login.py:46: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Web_Testing.Tests.test_signin.TestLogin object at 0x000002914FCD1B08>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with empty password\")\n    @allure.title(\"Login with empty password\")\n    @allure.description(\"Signing in with empty password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_5(self, setup):\n        logged_out_page = LoggedOutHome(self.driver)\n        logged_out_page.tb_login_btn.click()\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n        time.sleep(3)\n>       if lp.login_to_spotify(\"mohdos_1999@hotmail.com\", \"\"):\n\nTests\\test_signin.py:136: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages\\login.py:133: in login_to_spotify\n    exit('Testing failed in login with credentials : ' + email + \" & \" + password)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Use exit() or Ctrl-Z plus Return to exit, code = 'Testing failed in login with credentials : mohdos_1999@hotmail.com & '\n\n    def __call__(self, code=None):\n        # Shells like IDLE catch the SystemExit, but listen when their\n        # stdin wrapper is closed.\n        try:\n            sys.stdin.close()\n        except:\n            pass\n>       raise SystemExit(code)\nE       SystemExit: Testing failed in login with credentials : mohdos_1999@hotmail.com &\n\nC:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\\lib\\_sitebuiltins.py:26: SystemExit"}, "description": "Signing in with empty password", "start": 1584338063762, "stop": 1584338067906, "uuid": "6292cde4-d45d-4336-99d8-bea38ff3df4d", "historyId": "0793605ea697e46bb10c3cd4fc463cbd", "testCaseId": "be6e99c922d7bca5e3d8bf2c2d9fc37f", "fullName": "Tests.test_signin.TestLogin#test_case_5", "labels": [{"name": "subSuite", "value": "Login with empty password"}, {"name": "story", "value": "Failing login"}, {"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "4440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_signin"}]}