{"uuid": "883395c8-0d03-40c6-9616-ec3ba4a562ad", "children": ["c0b84f10-5e24-4d97-b46b-d6220d5b6ebf"], "befores": [{"name": "setup_final", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/signin&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\n\n", "trace": "  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\Web_Testing\\Tests\\test_login.py\", line 32, in setup_final\n    self.driver.get(self.link)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586147775027, "stop": 1586147777322}], "start": 1586147775027, "stop": 1586147777369}