{"name": "Login with correct credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'", "trace": "self = <Pages.login.LoginPage object at 0x0000029E0EB40748>, email = 'kamelmohsenkamel@gmail.com', password = 'Kimo2010'\n\n    def login_to_spotify(self, email, password):\n        try:\n>           self.WebDriverWait(self.driver, 10).until()\nE           AttributeError: 'LoginPage' object has no attribute 'WebDriverWait'\n\nPages\\login.py:75: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Tests.login_tests.Test object at 0x0000029E0EB40348>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Passing login\")\n    @allure.sub_suite(\"Login with correct credentials\")\n    @allure.title(\"Login with correct credentials\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: Kimo2010\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_1(self, setup):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"Kimo2010\"):\n\nTests\\login_tests.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Pages.login.LoginPage object at 0x0000029E0EB40748>, email = 'kamelmohsenkamel@gmail.com', password = 'Kimo2010'\n\n    def login_to_spotify(self, email, password):\n        try:\n            self.WebDriverWait(self.driver, 10).until()\n            sp = StatusPage(self.driver)\n            self.clear_page()\n            self.set_email(email)\n            self.set_password(password)\n            self.click_login()\n            time.sleep(2)\n    \n            if sp.check_status_page():\n                sp.click_web_player_link()\n                return True\n            else:\n                return False\n>       except (self.NoAlertPresentException, self.TimeoutException) as py_ex:\nE       AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'\n\nPages\\login.py:88: AttributeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: Kimo2010", "start": 1583932054118, "stop": 1583932054122, "uuid": "22cc073f-f402-45c7-bca9-23f5f6b6e613", "historyId": "778adf8990bbce17729561976a3427a2", "testCaseId": "33646af15c07e3a9e807d0b70f96b3f3", "fullName": "Tests.login_tests.Test#test_case_1", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "story", "value": "Passing login"}, {"name": "subSuite", "value": "Login with correct credentials"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "19196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}