{"name": "Login with wrong password", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'", "trace": "self = <Pages.login.LoginPage object at 0x0000021682CBB408>, email = 'kamelmohsenkamel@gmail.com', password = 'wrong password'\n\n    def login_to_spotify(self, email, password):\n        try:\n>           self.WebDriverWait(self.driver, 10).until()\nE           AttributeError: 'LoginPage' object has no attribute 'WebDriverWait'\n\nPages\\login.py:75: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Tests.login_tests.Test object at 0x00000216826E9488>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong password\")\n    @allure.title(\"Login with wrong password\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_2(self, setup):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"wrong password\"):\n\nTests\\login_tests.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Pages.login.LoginPage object at 0x0000021682CBB408>, email = 'kamelmohsenkamel@gmail.com', password = 'wrong password'\n\n    def login_to_spotify(self, email, password):\n        try:\n            self.WebDriverWait(self.driver, 10).until()\n            sp = StatusPage(self.driver)\n            self.clear_page()\n            self.set_email(email)\n            self.set_password(password)\n            self.click_login()\n            time.sleep(2)\n    \n            if sp.check_status_page():\n                sp.click_web_player_link()\n                return True\n            else:\n                return False\n>       except (self.NoAlertPresentException, self.TimeoutException) as py_ex:\nE       AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'\n\nPages\\login.py:88: AttributeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "start": 1583931984399, "stop": 1583931984405, "uuid": "4c4dc0a4-cf54-434c-90c1-be35f214c0cc", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "story", "value": "Failing login"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Log in Tests"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "12688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}