{"name": "Login with wrong email", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'", "trace": "self = <Pages.login.LoginPage object at 0x00000191FBA977C8>, email = 'kamelmohsenkamel', password = 'Kimo2010'\n\n    def login_to_spotify(self, email, password):\n        try:\n>           self.WebDriverWait(self.driver, 10).until()\nE           AttributeError: 'LoginPage' object has no attribute 'WebDriverWait'\n\nPages\\login.py:79: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Tests.login_tests.Test object at 0x00000191FBB0B8C8>, setup_final = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong email\")\n    @allure.title(\"Login with wrong email\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_3(self, setup_final):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel\", \"Kimo2010\"):\n\nTests\\login_tests.py:87: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Pages.login.LoginPage object at 0x00000191FBA977C8>, email = 'kamelmohsenkamel', password = 'Kimo2010'\n\n    def login_to_spotify(self, email, password):\n        try:\n            self.WebDriverWait(self.driver, 10).until()\n            sp = StatusPage(self.driver)\n            self.clear_page()\n            self.set_email(email)\n            self.set_password(password)\n            self.click_login()\n            time.sleep(2)\n    \n            if sp.check_status_page():\n                sp.click_web_player_link()\n                return True\n            else:\n                return False\n>       except (self.NoAlertPresentException, self.TimeoutException) as py_ex:\nE       AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'\n\nPages\\login.py:92: AttributeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "start": 1583932119977, "stop": 1583932119982, "uuid": "9e94b901-ee50-4b82-9318-12fbdd4322c8", "historyId": "25740cfebdb12bf5b1811f33adb157c7", "testCaseId": "394012d8fa57dbae71ee9d861bcf379b", "fullName": "Tests.login_tests.Test#test_case_3", "labels": [{"name": "subSuite", "value": "Login with wrong email"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Log in Tests"}, {"name": "suite", "value": "Login Tests"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "21024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}