{"name": "Login with wrong password", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'", "trace": "self = <Pages.login.LoginPage object at 0x00000191FBA86A88>, email = 'kamelmohsenkamel@gmail.com', password = 'wrong password'\n\n    def login_to_spotify(self, email, password):\n        try:\n>           self.WebDriverWait(self.driver, 10).until()\nE           AttributeError: 'LoginPage' object has no attribute 'WebDriverWait'\n\nPages\\login.py:79: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Tests.login_tests.Test object at 0x00000191FB1A9D08>, setup = None\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.story(\"Failing login\")\n    @allure.sub_suite(\"Login with wrong password\")\n    @allure.title(\"Login with wrong password\")\n    @allure.description(\"Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password\")\n    @pytest.mark.Do\n    @pytest.mark.Login\n    def test_case_2(self, setup):\n        lp = LoginPage(self.driver)\n        lp.check_login_page()\n>       if lp.login_to_spotify(\"kamelmohsenkamel@gmail.com\", \"wrong password\"):\n\nTests\\login_tests.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Pages.login.LoginPage object at 0x00000191FBA86A88>, email = 'kamelmohsenkamel@gmail.com', password = 'wrong password'\n\n    def login_to_spotify(self, email, password):\n        try:\n            self.WebDriverWait(self.driver, 10).until()\n            sp = StatusPage(self.driver)\n            self.clear_page()\n            self.set_email(email)\n            self.set_password(password)\n            self.click_login()\n            time.sleep(2)\n    \n            if sp.check_status_page():\n                sp.click_web_player_link()\n                return True\n            else:\n                return False\n>       except (self.NoAlertPresentException, self.TimeoutException) as py_ex:\nE       AttributeError: 'LoginPage' object has no attribute 'NoAlertPresentException'\n\nPages\\login.py:92: AttributeError"}, "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "start": 1583932116823, "stop": 1583932116828, "uuid": "78cb4318-d312-400d-b22d-18d112926a2f", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Log in Tests"}, {"name": "suite", "value": "Login Tests"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "21024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}