{"name": "Login with wrong password", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "attachments": [{"name": "SUCCESS: Login failed with incorrect credentials", "source": "ab85148f-6507-4394-9ff1-b6fccf5d6b03-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "b93144ec-f7d8-453b-aa3d-317e6fda6e99-attachment.txt", "type": "text/plain"}], "start": 1585784688810, "stop": 1585784696746, "uuid": "2fcd5aa9-9d2a-47e0-a9db-877fae44114d", "historyId": "56dc313029ecd9e7f1bb4370fcd7afd0", "testCaseId": "44a0190611d1e285bdb25958899fc986", "fullName": "Web_Testing.Tests.signin_tests.TestSignin#test_case_4", "labels": [{"name": "parentSuite", "value": "End to End testing"}, {"name": "severity", "value": "blocker"}, {"name": "story", "value": "Failing login"}, {"name": "suite", "value": "Login Tests"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "LAPTOP-8H6HECEC"}, {"name": "thread", "value": "35856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Web_Testing.Tests.signin_tests"}]}